---
name: Benchmarks

on:
  push:

jobs:
  benchmarks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.1']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run benchmarks
        run: bundle exec rake benchmark
